resources
| where type == "microsoft.keyvault/vaults"
| extend
    fullDetails = pack_all(),
    sku = strcat(properties.sku.family," - ",properties.sku.type),
    accessPolicies = iff(tobool(properties.enableRbacAuthorization), "Not used", properties.accessPolicies)
| join kind=leftouter (resourcecontainers | where type == "microsoft.resources/subscriptions") on subscriptionId
| project
    name,
    resourceGroup,
    subscription = name1,
    location,
    sku,
    publicNetworkAccess = properties.publicNetworkAccess,
    enableSoftDelete = properties.enableSoftDelete,
    softDeleteRetention = properties.softDeleteRetentionInDays,
    enableRBAC = properties.enableRbacAuthorization,
    accessPolicies,
    enablePurgeProtection = properties.enablePurgeProtection,
    creationTime = format_datetime(todatetime(systemData.createdAt), 'yyyy-MM-dd HH:mm:ss'),
    createdBy = systemData.createdBy,
    lastUpdateTime = format_datetime(todatetime(systemData.lastModifiedAt), 'yyyy-MM-dd HH:mm:ss'),
    lastUpdatedBy = systemData.lastModifiedBy,
    tags,
    fullDetails