resources
| where type == "microsoft.compute/disks"
| extend
    fullDetails = pack_all(),
    vmName = iff(isnotempty(managedBy), split(managedBy, "/")[-1], "Not attached to VM")
| project
    name,
    vmName,
    resourceGroup,
    sku = sku.name,
    size = properties.diskSizeGB,
    state = properties.diskState,
    creationTime = format_datetime(todatetime(properties.timeCreated), 'yyyy-MM-dd HH:mm:ss'),
    tags,
    fullDetails
